name: Frontend Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    timeout-minutes: 60
    name: Build frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set node version and start backend
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: yarn install
        working-directory: manage_backend

      - name: Setup frontend
        run: yarn install
        working-directory: manage_frontend

      - name: Start PostgreSQL with Docker
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          services: postgres
          compose-file: "docker-compose.test.yml"

      - name: Wait for Postgres to be ready
        id: wait-postgres
        run: |
          sleep 10
          set -e
          attempt=0
          max_attempts=10
          while [ "$attempt" -lt "$max_attempts" ]; do
            sleep 5
            pg_isready -h localhost -p 5432 && break
            attempt=$((attempt+1))
            echo "Waiting for Postgres..."
          done
          if [ "$attempt" -eq "$max_attempts" ]; then
            echo "PostgreSQL did not start in time"
            exit 1
          fi
          echo "PostgreSQL database is ready"

      - name: Get Docker logs if Postgres server fails
        if: failure() && steps.wait-postgres.outcome != 'success'
        run: docker logs friendly-spork-postgres-1

      - name: Create test database and user
        run: |
          export PGPASSWORD=${{ secrets.TEST_DB_PASSWORD }}
          attempt=0
          max_attempts=5
          while [ "$attempt" -lt "max_attempts" ]; do
            psql -h localhost -U ${{ secrets.TEST_DB_USER }} -c "CREATE DATABASE IF NOT EXISTS test_manage;" && break
            attempt=$((attempt+1))
            sleep 2
            echo 'Retrying database connection...'
          done
          if [ "$attempt" -eq "$max_attempts" ]; then
            echo 'Failed to connect to database after multiple attempts.'
            exit 1
          fi

          attempt=0
          max_attempts=5
          while [ "$attempt" -lt "$max_attempts" ]; do
            psql -h localhost -U ${{ secrets.TEST_DB_USER }} -d test_manage -c "CREATE USER IF NOT EXISTS test_user WITH PASSWORD "${{ secrets.TEST_APP_PASSWORD }}";" && break
            attempt=$((attempt+1))
            sleep 2
            echo 'Retrying to create user...'
          done
          if [ "$attempt" -eq "max_attempts" ]; then
            echo "Failed to create user"
            exit 1
          fi

          attempt=0
          max_attempts=5
          while [ "$attempt" -lt "$max_attempts" ]; do
            psql -h localhost -U postgres -d test_manage -c "GRANT ALL PRIVILEGES ON DATABASE test_manage TO test_user;" && break
            attempt=$((attempt+1))
            sleep 2
            echo 'Retrying to grant privileges...'
          done
          if [ "$attempt" -eq "max_attempts" ]; then
            echo "Failed to grant privileges"
            exit 1
          fi

      - name: Run Drizzle Kit migration
        run: |
          export DATABASE_URL="postgresql://test_user:${{secrets.TEST_DB_PASSWORD}}@localhost:5432/test_manage"
          yarn run start:ci > backend.log 2>&1 &
        working-directory: manage_backend
        env:
          JWT_SECRET: ${{secrets.JWT_SECRET}}
        timeout-minutes: 5

      - name: Wait for backend to be ready
        run: sleep 10

      - name: Setup Playwright
        run: npx playwright install --with-deps
        working-directory: manage_frontend

      - name: Run Playwright tests
        run: yarn run ci-test
        working-directory: manage_frontend
        env:
          MANAGE_BACKEND: ${{secrets.MANAGE_BACKEND}}
          PLAYWRIGHT_TEST_EMAIL: ${{secrets.PLAYWRIGHT_TEST_EMAIL}}
          PLAYWRIGHT_TEST_PASSWORD: ${{secrets.PLAYWRIGHT_TEST_PASSWORD}}
          DATABASE_URL: "postgresql://${{secrets.TEST_DB_USER}}:${{secrets.TEST_DB_PASSWORD}}@localhost:5432/test_manage"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: manage_frontend/playwright-report/
          retention-days: 30

      - name: Output backend logs if there is a failure
        if: failure()
        run: cat manage_backend/backend.log
