name: Frontend Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    timeout-minutes: 60
    name: Build frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set node version and start backend
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: yarn install
        working-directory: manage_backend
      - run: yarn run start:ci &
        working-directory: manage_backend
        env:
          DB_FILE_NAME: file:test_db.db
        timeout-minutes: 5

      - name: Setup frontend
        run: yarn install
        working-directory: manage_frontend

      - name: Setup Playwright
        run: npx playwright install --with-deps
        working-directory: manage_frontend

      - name: Print environment variables
        run: printenv
        working-directory: manage_frontend

      # - name: Start devserver
      #   run: yarn run devtest &
      #   working-directory: manage_frontend

      # - run: sleep 60

      - name: Run Playwright tests
        run: yarn run test
        working-directory: manage_frontend
        env:
          MANAGE_BACKEND: ${{secrets.MANAGE_BACKEND}}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
